#!/usr/bin/env bash
set -eo pipefail

TEMPLATE='{{tablerow "Num" "Title" "Who" "URL" "When" -}}
{{range(pluck "node" .data.search.edges) -}}
{{tablerow (printf "#%v" .number | autocolor "green") .title .author.login (.url | autocolor "cyan") (timeago .createdAt)  -}}
{{end -}}
{{tablerender}}'
GH_REST_API_VERSION="X-GitHub-Api-Version: 2022-11-28"
GH_ACCEPT="Accept: application/vnd.github+json"
export GH_PAGER="cat"

function gh_api() {
  gh api -H "$GH_REST_API_VERSION" -H "$GH_ACCEPT" "$@"
}

function query_help()
{
  cat << EOF

Usage: gh my [issues|prs|reviews|workload|report|deployments|notifs|failures] [options]
  issues      : list issues in your personal repositories
  prs         : list PRs in your persional repositories
  reviews     : list PRs where you've been asked for a review
  workload    : list PRs and issues where you are the assignee
  deployments : list deployments awaiting action on the default branch
  report      : show all the issues & prs you've been involved in the last 14 days
                (because you have to tell people what you've done)
  notifs      : list unread notifications
  failures    : show workflow failures in your repos

Listing deployments needs more filters
  -o : the organisation (e.g. -o my-company)
  -t : the topic  (e.g. -o my-terraform-repos)
  -r : a specific repository, but why not use gh run list instead?

Report generation uses 'date' so any gnu date string is valid
  -d : the date string (default is "14 days ago")
  -q : omit the table headers
  -a : use 'author' instead of 'involves'
  -v : everything involving your user (e.g. where you're a CODEOWNER)

Failure generation uses 'date' so any gnu date string is valid
  -d : the date string (default is "14 days ago")

Listing notifications can also mark them as read
  -n : the ID to mark as read (-n 7235590448)
  -a : Mark all notifications as read

EOF
 exit 1
}

function query_workload() {
  # shellcheck disable=SC2016
  query='query ($endCursor: String){
          search(query: "is:open assignee:@me archived:false",after: $endCursor, type: ISSUE, first: 50) {
            edges {
              node {
                ... on PullRequest {
                  number
                  title
                  author {
                    login
                  }
                  reviewDecision
                  createdAt
                  url
                  repository {
                    nameWithOwner
                    name
                  }
                }
                ... on Issue {
                  number
                  title
                  author {
                    login
                  }
                  createdAt
                  url
                  repository {
                    nameWithOwner
                    name
                  }
                }
              }
            }
            pageInfo {
              hasNextPage
              endCursor
            }
          }
        }'
  gh api graphql --paginate --raw-field query="$(internal::compressQuery "$query")" --template "$TEMPLATE"
}

function query_reviews() {
  # shellcheck disable=SC2016
  query='query ($endCursor: String){
          search(query: "is:open is:pr review-requested:@me archived:false", after: $endCursor, type: ISSUE, first: 50) {
            edges {
              node {
                ... on PullRequest {
                  number
                  title
                  author {
                     login
                  }
                  reviewDecision
                  createdAt
                  url
                  repository {
                    nameWithOwner
                    name
                  }
                }
              }
            }
            pageInfo {
              hasNextPage
              endCursor
            }
          }
        }'
  gh api graphql --paginate --raw-field query="$(internal::compressQuery "$query")" --template "$TEMPLATE"
}

function query_issues() {
  # shellcheck disable=SC2016
  query='query ($endCursor: String) {
          search(query: "is:open is:issue user:@me archived:false", type: ISSUE, after: $endCursor, first: 50) {
            edges {
              node {
                ... on Issue {
                  number
                  title
                  author {
                    login
                  }
                  createdAt
                  url
                  repository {
                    nameWithOwner
                    name
                  }
                }
              }
            }
            pageInfo {
              hasNextPage
              endCursor
            }
          }
        }'
  gh api graphql --paginate --raw-field query="$(internal::compressQuery "$query")" --template "$TEMPLATE"
}

function query_prs() {
  # shellcheck disable=SC2016
  query='query ($endCursor: String) {
          search(query: "is:open is:pr user:@me archived:false", type: ISSUE, after: $endCursor, first: 50) {
            edges {
              node {
                ... on PullRequest {
                  number
                  title
                  author {
                    login
                  }
                  createdAt
                  url
                  repository {
                    nameWithOwner
                    name
                  }
                }
              }
            }
            pageInfo {
              hasNextPage
              endCursor
            }
          }
        }'
  gh api graphql --paginate --raw-field query="$(internal::compressQuery "$query")" --template "$TEMPLATE"
}

function query_deployments() {
  org=''
  topic=''
  repo=''
  while getopts 'o:t:r:' flag; do
    case "${flag}" in
    o) org="org:${OPTARG}" ;;
    t) topic="topic:${OPTARG}" ;;
    r) repo="${OPTARG}" ;;
    *) query_help ;;
    esac
  done
  if [[ "$org" == "" && $topic = "" && $repo = "" ]]; then
    query_help
  fi
  if [[ $repo != "" ]]; then
    internal::repo_deploys "$repo"
  else
    queryString="$org $topic"
    internal::org_deploys "$queryString"
  fi
}

# Get all the issues & PRs involving by me in the last 14 days.
function query_report() {
  report_header='{{tablerow "Num" "Title" "Repository" "URL" "Last Activity" -}}'
  report_data='
{{range(pluck "node" .data.search.edges) -}}
{{tablerow (printf "#%v" .number | autocolor "green") .title (.repository.nameWithOwner | autocolor "yellow") (.url | autocolor "cyan") (timefmt "02-Jan" .updatedAt)  -}}
{{end -}}
{{tablerender}}
'
  # This catches PRs where I have been requested as a reviewer, but I did nothing (CODEOWNER)
  user_filter="involves:@me -user-review-requested:@me"
  include_headers=true
  since='14 days ago'
  while getopts 'd:qav' flag; do
    case "${flag}" in
    d) since="${OPTARG}" ;;
    a) user_filter="author:@me" ;;
    v) user_filter="involves:@me" ;;
    q) include_headers=false ;;
    *) query_help ;;
    esac
  done

  report_template="$report_data"
  if [[ "$include_headers" == "true" ]]; then
    report_template="$report_header $report_data"
  fi
  queryString="$user_filter updated:>=$(date --date="$since" '+%Y-%m-%d') archived:false sort:updated"
  # shellcheck disable=SC2016
  query='query ($queryString: String!, $endCursor: String){
          search(query: $queryString,after: $endCursor, type: ISSUE, first: 50) {
            edges {
              node {
                ... on PullRequest {
                  number
                  title
                  author {
                    login
                  }
                  reviewDecision
                  updatedAt
                  url
                  repository {
                    nameWithOwner
                  }
                }
                ... on Issue {
                  number
                  title
                  author {
                    login
                  }
                  updatedAt
                  url
                  repository {
                    nameWithOwner
                  }
                }
              }
            }
            pageInfo {
              hasNextPage
              endCursor
            }
          }
        }'
  gh api graphql --paginate -F queryString="$queryString" --raw-field query="$(internal::compressQuery "$query")" --template "$report_template"
}

function query_notifs() {
  notif_template='{{tablerow "ID" "Reason" "When" "Repo" "Title" -}}
{{ range . -}}
{{tablerow (.id | autocolor "green") (.reason | autocolor "cyan") (timeago .updated_at) (.repository.full_name) (hyperlink "https://github.com/notifications" (.subject.title | autocolor "yellow")) -}}
{{end -}}'

  notif_id=''
  mark_all_as_read=''
  while getopts 'n:a' flag; do
    case "${flag}" in
    n) notif_id="${OPTARG}" ;;
    a) mark_all_as_read="yes" ;;
    *) query_help ;;
    esac
  done

  if [[ -z "$notif_id" && -z "$mark_all_as_read" ]]; then
    # Show notifications
    gh api notifications --template "$notif_template"
  fi
  if [[ -n "$notif_id" ]]; then
    gh api "notifications/threads/$notif_id" --method PATCH --silent
  fi
  if [[ -n "$mark_all_as_read" ]]; then
    gh api "notifications" --method PUT --silent
  fi

}


# Query a specific repo for any deployments that are in a "waiting" state
function internal::repo_deploys() {
  repo="$1"
  # shellcheck disable=SC2016
  deploy_template='{{tablerow "ID" "URL" "Branch" "When" -}}
{{ range . -}}
{{tablerow (.databaseId | autocolor "green") (.url | autocolor "cyan") (.headBranch | autocolor "yellow") (timeago .startedAt) -}}
{{end -}}'
  gh run list --repo "$repo" --json "databaseId,url,headBranch,startedAt" --template "$deploy_template" -s "waiting"
}

# Query the org, (filtering by topic) listing deploymens in a waiting state that on the default branch
function internal::org_deploys() {
  queryString="$1"
  # shellcheck disable=SC2016
  deploy_template='{{tablerow "ID" "URL" "Branch" "Repo" "Env" "Actionable" "When" -}}
{{range(pluck "node" .data.search.edges) -}}
{{ $repo:=.nameWithOwner -}}{{ $branch:=.defaultBranchRef.name -}}
{{range(pluck "workflowRun" .defaultBranchRef.target.checkSuites.nodes) -}}{{ $workflowId:= .databaseId -}}{{ $workflowRunURL:= .url -}}
{{range .checkSuite.checkRuns.nodes -}}
{{tablerow ($workflowId | autocolor "green")
          ($workflowRunURL | autocolor "cyan")
          ($branch | autocolor "yellow")
          $repo
          .pendingDeploymentRequest.environment.name
          .pendingDeploymentRequest.currentUserCanApprove
          (timeago .startedAt) -}}
{{end -}}
{{end -}}
{{end -}}
'
  # shellcheck disable=SC2016
  query='query ($queryString: String!, $endCursor: String) {
  search(query: $queryString, type: REPOSITORY, first: 100, after: $endCursor) {
    edges {
      node {
        ... on Repository {
          nameWithOwner
          defaultBranchRef {
            name
            target {
              ... on Commit {
                checkSuites(filterBy: {appId: 15368}, last: 1) {
                  nodes {
                    workflowRun {
                      databaseId
                      url
                      checkSuite {
                        checkRuns(filterBy: {status: WAITING}, last: 1) {
                          nodes {
                            startedAt
                            pendingDeploymentRequest {
                              environment {
                                name
                              }
                              currentUserCanApprove
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}'
  gh api graphql --paginate -F queryString="$queryString" --raw-field query="$(internal::compressQuery "$query")" --template "$deploy_template"
}

# Query your repos for workflow failures
query_failures() {
  local since='14 days ago'
  while getopts 'd:' flag; do
    case "${flag}" in
    d) since="${OPTARG}" ;;
    esac
  done
  local since_epoch=$(date -d "$since" "+%s")
  local jq_filter=$(cat <<-EOF
  .workflow_runs[] |  select ((.created_at | fromdateiso8601) > $since_epoch) |
  "\(.repository.name)|\(.name)|\(.html_url)|\(.created_at | fromdateiso8601 | strflocaltime("%d %b %Y"))"
EOF
  )
  local gh_repos=$(gh repo list --json "nameWithOwner" -q ".[] | .nameWithOwner")
  {
    for gh_repo in $gh_repos; do
      failed_workflows=$(gh_api "repos/$gh_repo/actions/runs?status=failure")
      echo "$failed_workflows" | jq -r "$jq_filter"
    done
  } | column -s'|' -t -N "REPOSITORY,WORKFLOW,URL,WHEN"

}

# This is clearly a bout of premature optimisation and saving
# a few newlines & spaces shouldn't be high on anyone's list
function internal::compressQuery() {
  echo "$1" | tr -d '\n'
}


ACTION=$1 || true
ACTION=${ACTION:="help"}
if [[ "$#" -ne "0" ]]; then shift; fi
"query_${ACTION}" "$@"

