#!/usr/bin/env bash

export GH_PAGER="cat"
GH_REST_API_VERSION="X-GitHub-Api-Version: 2022-11-28"
GH_ACCEPT="Accept: application/vnd.github+json"

#shellcheck disable=SC2034
STD_TABLE_TEMPLATE='{{tablerow "Num" "Title" "Who" "URL" "When" -}}
{{range(pluck "node" .data.search.edges) -}}
{{tablerow (printf "#%v" .number | autocolor "green") .title .author.login (.url | autocolor "cyan") (timeago .createdAt)  -}}
{{end -}}
{{tablerender}}'

STD_JQ_FILTER='.data.search.edges[] | .node | { "number":.number, "title": .title, "login": .author.login, "url": .url, "createdAt": .createdAt}'
STD_OUTPUT_FORMAT="table"

# shellcheck disable=SC2016
MY_ORGS_QUERY='query ($after: String) { viewer { organizations(first: 100, after: $after) { edges { cursor node { login } } pageInfo { hasNextPage endCursor } } } }'
MY_ORGS_FLATTEN_JQ='.data.viewer.organizations.edges[] | .node.login'
MY_ORGS_EXCLUDE="${GH_MY_IGNORE_ORGS:-}"

helper::gh_api() {
  gh api -H "$GH_REST_API_VERSION" -H "$GH_ACCEPT" "$@"
}

helper::compressQuery() {
  echo "$1" | tr -s ' ' | tr -d '\n'
}

helper::std_output_format() {
  local query="$1"
  while getopts 'j' flag; do
    case "${flag}" in
    j) STD_OUTPUT_FORMAT="json" ;;
    *) query_help ;;
    esac
  done
}

helper::std_graphql() {
  local query="$1"
  case $STD_OUTPUT_FORMAT in
  json)
    gh api graphql --paginate --raw-field query="$(helper::compressQuery "$query")" --jq "$STD_JQ_FILTER" | jq -c "."
    ;;
  *)
    gh api graphql --paginate --raw-field query="$(helper::compressQuery "$query")" --template="$STD_TABLE_TEMPLATE"
    ;;
  esac
}

helper::giturl_to_base() {
  local url=$1
  url=${url%%.git}
  url=${url#*github.com:}
  url=${url#*github.com/}
  echo "$url"
}

helper::my_github_orgs() {
  local myorgs=""
  local filtered_orgs=()
  myorgs=$(gh api graphql --paginate --raw-field query="$(helper::compressQuery "$MY_ORGS_QUERY")" --jq "$MY_ORGS_FLATTEN_JQ")
  for org in $myorgs; do
    skip_org=false
    for exclude_org in $MY_ORGS_EXCLUDE; do
      if [[ "$org" == "$exclude_org" ]]; then
        skip_org=true
        break
      fi
    done
    if [[ "$skip_org" != "true" ]]; then
      filtered_orgs+=("$org")
    fi
  done
  echo "${filtered_orgs[@]}"
}

helper::gh_whoami() {
  local me=""
  me=$(gh config get user -h github.com 2>/dev/null || true)
  if [[ -z "$me" ]]; then
    me=$(gh auth status -h github.com | grep "Logged in" | sed -e "s/^[[:blank:]]*//" -e "s/[[:blank:]]*$//" | cut -f7 -d ' ')
  fi
  echo "$me"
}
