#!/usr/bin/env bash

query_prs_help() {
  cat <<EOF

Usage: gh my prs [options]
  list PRs in the current repository or all your personal repos

  -a            : PRs in all your personal repositories
                  This is the default behaviour if your current location
                  is not a github repo and should be explicitly set if
                  it is.
  -j            : output each row as a JSON object.
  -o --org      : the PRs belonging to the associated organisation
                  e.g. gh my prs -o my-company
  -g --all-orgs : ALL organisations that you belong to. This is potentially a time-consuming
                  and foolish move, so you have been warned.
                  To mitigate, you can also set 'GH_MY_IGNORE_ORGS' as an additional filter
                  (space separated), but the filter isn't that sophisticated.
  -u            : reduce the output so that the URL is primary
                  maybe you dislike 'gh my prs -j | jq -r '.url' | xargs -r L1 gh pr view -w'

 Environment:
  'GH_MY_PRS_QUERY_EXTRAS' - this environment variable is appended to the prs query so you
                             can do something like "-label:backlog" to filter the query.
EOF
  exit 2
}

PR_ALL_REPOS_QUERY="is:open is:pr user:@me archived:false"
PR_ORG_REPOS_QUERY="is:open is:pr org:__MYORG__ archived:false"
#shellcheck disable=SC2034
#shellcheck disable=SC2016
PR_QUERY_TABLE_FORMAT='{{tablerow "" "Num" "Title" "Who" "URL" "When" -}}
  {{range(pluck "node" .data.search.edges) -}}
  {{ $status := "❔" -}}
  {{ $review := "🌤️" -}}
  {{ if index . "reviewDecision" -}}
    {{ if eq .reviewDecision "CHANGES_REQUESTED" -}}
      {{ $review = "✒️" -}}
    {{ end -}}
    {{ if eq .reviewDecision "REVIEW_REQUIRED" -}}
      {{ $review = "👀" -}}
    {{ end -}}
    {{ if eq .reviewDecision "APPROVED" -}}
      {{ $review = "👍" -}}
    {{ end -}}
  {{ end -}}
  {{ if index . "statusCheckRollup" -}}
    {{ if eq .statusCheckRollup.state "PENDING" -}}
      {{ $status = "⏱️" -}}
    {{ end -}}
    {{ if eq .statusCheckRollup.state "FAILURE" -}}
      {{ $status = "⛔" -}}
    {{ end -}}
    {{ if eq .statusCheckRollup.state "SUCCESS" -}}
      {{ $status = "✅" -}}
    {{ end -}}
  {{ end -}}
  {{ $draft := "🛫" -}}
  {{ if eq .isDraft true -}}
    {{ $draft = "🔨" -}}
  {{ end -}}
  {{tablerow ( printf "%s%s%s" $status $review $draft) (printf "#%v" .number | autocolor "green") .title .author.login (.url | autocolor "cyan") (timeago .createdAt)  -}}
  {{end -}}
  {{tablerender}}'

# Where the URL is more important.
#shellcheck disable=SC2016
PR_QUERY_URL_FORMAT='{{tablerow "" "URL" "Title" "Who" -}}
  {{range(pluck "node" .data.search.edges) -}}
  {{ $status := "❔" -}}
  {{ $review := "🌤️" -}}
  {{ if index . "reviewDecision" -}}
    {{ if eq .reviewDecision "CHANGES_REQUESTED" -}}
      {{ $review = "✒️" -}}
    {{ end -}}
    {{ if eq .reviewDecision "REVIEW_REQUIRED" -}}
      {{ $review = "👀" -}}
    {{ end -}}
    {{ if eq .reviewDecision "APPROVED" -}}
      {{ $review = "👍" -}}
    {{ end -}}
  {{ end -}}
  {{ if index . "statusCheckRollup" -}}
    {{ if eq .statusCheckRollup.state "PENDING" -}}
      {{ $status = "⏱️" -}}
    {{ end -}}
    {{ if eq .statusCheckRollup.state "FAILURE" -}}
      {{ $status = "⛔" -}}
    {{ end -}}
    {{ if eq .statusCheckRollup.state "SUCCESS" -}}
      {{ $status = "✅" -}}
    {{ end -}}
  {{ end -}}
  {{ $draft := "🛫" -}}
  {{ if eq .isDraft true -}}
    {{ $draft = "🔨" -}}
  {{ end -}}
  {{tablerow ( printf "%s%s%s" $status $review $draft) (.url | autocolor "cyan") (.title | truncate 30) (.author.login | truncate 20) -}}
  {{end -}}
  {{tablerender}}'

# shellcheck disable=SC2016
QUERY_PR_GRAPHQL='
query ($queryString: String!,$endCursor: String) {
  search(query: $queryString, type: ISSUE, after: $endCursor, first: 50) {
    edges {
      node {
        ... on PullRequest {
          number
          title
          author {
            login
          }
          createdAt
          url
          repository {
            nameWithOwner
            name
          }
          statusCheckRollup {
            state
          }
          reviewDecision
          isDraft
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}'
QUERY_JQ_FILTER='.data.search.edges[] | .node | { "number":.number, "title": .title, "login": .author.login, "statusRollup": .statusCheckRollup.state, "reviewDecision": .reviewDecision, "isDraft": .isDraft, "url": .url, "createdAt": .createdAt}'

_prs_repo_query() {
  local gitRemote=""
  local queryExtras="${GH_MY_PRS_QUERY_EXTRAS:-}"
  if helper::is_repo; then
    gitRemote=$(helper::repo_info)
  fi
  if [[ -n "$gitRemote" ]]; then
    echo "is:open is:pr repo:$gitRemote archived:false $queryExtras"
  else
    echo "$PR_ALL_REPOS_QUERY $queryExtras"
  fi
}

_prs_org_query() {
  local org="$1"
  local queryExtras="${GH_MY_PRS_QUERY_EXTRAS:-}"
  echo "${PR_ORG_REPOS_QUERY//"__MYORG__"/"${org}"} $queryExtras"
}

_prs_do_query() {
  local queryString="$1"
  local outputFormat="$2"
  local urlFirst="$3"
  local template="$PR_QUERY_TABLE_FORMAT"

  if [[ "$urlFirst" == "true" ]]; then
    template="$PR_QUERY_URL_FORMAT"
  fi
  case $outputFormat in
  json)
    gh api graphql --paginate -F queryString="$queryString" --raw-field query="$(helper::compressQuery "$QUERY_PR_GRAPHQL")" --jq "$QUERY_JQ_FILTER" | jq -c "."
    ;;
  *)
    gh api graphql --paginate -F queryString="$queryString" --raw-field query="$(helper::compressQuery "$QUERY_PR_GRAPHQL")" --template "$template"
    ;;
  esac
}

# Because of https://github.com/orgs/community/discussions/24375
# reviewDecision will only be populated IF a review is 'required'
# otherwise it defaults to null. ? in that context is potentially
# a distracting emoji.
query_prs() {
  local queryString
  local queryAllOrgs="false"
  local outputFormat="table"
  local urlFirst="false"

  queryString=$(_prs_repo_query)
  for arg in "$@"; do
    shift
    case "$arg" in
    '--org')
      set -- "$@" '-o'
      ;;
    '--all')
      set -- "$@" '-a'
      ;;
    *)
      set -- "$@" "$arg"
      ;;
    esac
  done

  while getopts 'o:jaguh' flag; do
    case "${flag}" in
    a)
      queryString="$PR_ALL_REPOS_QUERY"
      ;;
    o)
      if [[ -z "${OPTARG}" ]]; then
        echo "Error: -o requires a non-empty organization name"
        query_help
      fi
      queryString=$(_prs_org_query "${OPTARG}")
      ;;
    j)
      outputFormat="json"
      ;;
    g)
      queryAllOrgs="true"
      ;;
    u)
      urlFirst="true"
      ;;
    h)
      query_prs_help
      ;;
    *)
      query_prs_help
      ;;
    esac
  done

  if [[ "$queryAllOrgs" == "true" ]]; then
    helper::for_each_my_github_org "$outputFormat" _prs_query_org "$urlFirst"
  else
    _prs_do_query "$queryString" "$outputFormat" "$urlFirst"
  fi
}

_prs_query_org() {
  local org="$1"
  local outputFormat="$2"
  local urlFirst="$3"
  local queryString=""

  queryString="$(_prs_org_query "$org")"
  _prs_do_query "$queryString" "$outputFormat" "$urlFirst"
}
