#!/usr/bin/env bash

query_reviews_help() {
  cat <<EOF

Usage: gh my reviews [options]
  list PRs where you've been asked for a review

  -j : output each row as a JSON object.
       (--jsonlines is also accepted)
EOF
  exit 2
}

query_reviews() {
  for arg in "$@"; do
    case "$arg" in
    -h) query_reviews_help ;;
    esac
  done
  # shellcheck disable=SC2016
  local query='
query ($endCursor: String){
  search(query: "is:open is:pr review-requested:@me archived:false", after: $endCursor, type: ISSUE, first: 50) {
    edges {
      node {
        ... on PullRequest {
          number
          title
          author {
             login
          }
          reviewDecision
          createdAt
          url
          repository {
            nameWithOwner
            name
          }
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}'
  helper::std_output_format "$@"
  helper::std_graphql "$query"
}
