#!/usr/bin/env bash
query_workload() {
  # shellcheck disable=SC2016
  local query='
query ($endCursor: String){
  search(query: "is:open assignee:@me archived:false",after: $endCursor, type: ISSUE, first: 50) {
    edges {
      node {
        ... on PullRequest {
          number
          title
          author {
            login
          }
          reviewDecision
          createdAt
          url
          repository {
            nameWithOwner
            name
          }
        }
        ... on Issue {
          number
          title
          author {
            login
          }
          createdAt
          url
          repository {
            nameWithOwner
            name
          }
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}'
  helper::std_output_format "$@"
  helper::std_graphql "$query"
}
