#!/usr/bin/env bash

query_workload_help() {
  cat <<EOF

Usage: gh my workload [options]
  list PRs and issues where you are the assignee

  -j : output each row as a JSON object.
       (--jsonlines is also accepted)
EOF
  exit 2
}

query_workload() {
  for arg in "$@"; do
    case "$arg" in
    -h) query_workload_help ;;
    esac
  done
  # shellcheck disable=SC2016
  local query='
query ($endCursor: String){
  search(query: "is:open assignee:@me archived:false",after: $endCursor, type: ISSUE, first: 50) {
    edges {
      node {
        ... on PullRequest {
          number
          title
          author {
            login
          }
          reviewDecision
          createdAt
          url
          repository {
            nameWithOwner
            name
          }
        }
        ... on Issue {
          number
          title
          author {
            login
          }
          createdAt
          url
          repository {
            nameWithOwner
            name
          }
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}'
  helper::std_output_format "$@"
  helper::std_graphql "$query"
}
