#!/usr/bin/env bash
set -eo pipefail

query_vulns_help() {
  cat <<EOF

Usage: gh my vulns [options]
  show vulnerability alerts from dependabot in the current repository
  or your personal repositories

  -g --all-orgs : ALL organisations that you belong to. This is potentially a time-consuming
                  and foolish move, so you have been warned.
                  To mitigate, you can also set 'GH_MY_IGNORE_ORGS' as an additional filter
                  (space separated), but the filter isn't that sophisticated.
  -a : vulnerabilities in all your personal repositories
       This is the default behaviour if your current location
       is not a github repo and should be explicitly set if
       it is.
  -o : the owner (e.g. -o my-company | -o my-user)
       default is whatever 'gh config get user -h github.com' returns
       ** Viewing security alerts implies permissions
  -j : output each row as a JSON object.
EOF
  exit 2
}

# shellcheck disable=SC2016
VULNS_JSON_JQ='
.data.search.edges[] | .node.vulnerabilityAlerts.nodes.[] |
{
    "repository": .repository.nameWithOwner,
    "package": .securityVulnerability.package.name,
    "severity": .securityVulnerability.severity,
    "CVE": (.securityAdvisory.identifiers // [] | map(select(.type == "CVE")) | .[0].value) // null,
    "GHSA": .securityAdvisory.ghsaId,
    "url": "https://github.com/\(.repository.nameWithOwner)/security/dependabot/\(.number)",
    "createdAt": .createdAt
}
'

# shellcheck disable=SC2016
VULNS_REPORT_TEMPLATE='
{{tablerow "Repository" "Package" "CVE" "GHSA" "Severity" "URL" "Created" -}}
{{range(pluck "node" .data.search.edges) -}}
{{range .vulnerabilityAlerts.nodes -}}
{{ $url:= printf "https://github.com/%s/security/dependabot/%v" .repository.nameWithOwner .number -}}
{{ $cve:= "n/a" -}}
{{range .securityAdvisory.identifiers -}}
  {{ if eq .type "CVE" -}}
    {{ $cve = .value -}}
  {{ end -}}
{{ end -}}
{{tablerow (.repository.nameWithOwner | autocolor "green")
          (.securityVulnerability.package.name | autocolor "cyan")
          ($cve | autocolor "yellow")
          (.securityAdvisory.ghsaId | autocolor "yellow")
          (.securityVulnerability.severity)
          ($url | autocolor "blue")
          (timeago .createdAt) -}}
{{end -}}
{{end -}}
'
# shellcheck disable=SC2016
VULNS_GRAPHQL_QUERY='
query($searchQuery: String!, $endCursor: String) {
  search(query: $searchQuery, type: REPOSITORY, first: 100, after: $endCursor) {
    edges {
      node {
        ... on Repository {
          nameWithOwner
          vulnerabilityAlerts(first: 100, states:OPEN) {
            nodes {
              createdAt
              vulnerableManifestPath
              vulnerableManifestFilename
              number
              repository {
                nameWithOwner
              }
              securityVulnerability {
                package {
                  name
                }
                severity
              }
              securityAdvisory {
                ghsaId
                identifiers {
                  type
                  value
                }
              }
            }
          }
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
'

query_vulns() {

  local owner=""
  local output_format="table"
  local query_all_orgs="false"
  local my_orgs=""
  local queryString=""
  owner=$(helper::gh_whoami)
  while getopts 'go:jah' flag; do
    case "${flag}" in
    g) query_all_orgs="true" ;;
    j) output_format="json" ;;
    o)
      # Explicit owner then you know what you're doing?
      owner="${OPTARG}"
      ;;
    a) ;;
    h) query_vulns_help ;;
    *) query_vulns_help ;;
    esac
  done

  if [[ "$query_all_orgs" == "true" ]]; then
    my_orgs=$(helper::my_github_orgs)
    for org in $my_orgs; do
      queryString="owner:$org fork:true archived:false"
      if [[ "$output_format" != "json" ]]; then
        echo -e "\n🏛️ $org"
      fi
      case $output_format in
      json)
        gh api graphql --paginate -F searchQuery="$queryString" --raw-field query="$(helper::compressQuery "$VULNS_GRAPHQL_QUERY")" --jq="$VULNS_JSON_JQ" | jq -c "."
        ;;
      *)
        gh api graphql --paginate -F searchQuery="$queryString" --raw-field query="$(helper::compressQuery "$VULNS_GRAPHQL_QUERY")" --template="$VULNS_REPORT_TEMPLATE"
        ;;
      esac
    done <<<"$my_orgs"
    echo ""
  else
    queryString="owner:$owner fork:true archived:false"
    case $output_format in
    json)
      gh api graphql --paginate -F searchQuery="$queryString" --raw-field query="$(helper::compressQuery "$VULNS_GRAPHQL_QUERY")" --jq="$VULNS_JSON_JQ" | jq -c "."
      ;;
    *)
      gh api graphql --paginate -F searchQuery="$queryString" --raw-field query="$(helper::compressQuery "$VULNS_GRAPHQL_QUERY")" --template="$VULNS_REPORT_TEMPLATE"
      ;;
    esac
  fi
}
