#!/usr/bin/env bash

query_help() {
  cat <<EOF

Usage: gh my [$ACTION_LIST] [options]
  alerts      : show open dependabot alerts in the current repository
  issues      : list issues in your personal repositories
  prs         : list PRs in the current repository or all your personal repos
  reviews     : list PRs where you've been asked for a review
  workload    : list PRs and issues where you are the assignee
  deployments : list deployments awaiting action on the default branch
  report      : show all the issues & prs you've been involved in the last 14 days
                (because you have to tell people what you've done)
  notifs      : list unread notifications
  failures    : show workflow failures in your personal repositories in the last 14 days
  vulns       : show vulnerability alerts from dependabot in the current repository
                or your personal repositories
  orgs        : show the organisations you belong to

Use 'gh my <command> --help' for more information about a specific command.

Environment Variables:
GH_MY_PRS_QUERY_EXTRAS : additional query to add to 'my prs'
GH_MY_IGNORE_ORGS      : to ignore organisations that you belong to
EOF
  exit 2
}
