#!/usr/bin/env bash
# Query your repos for workflow failures

query_failures_help() {
  cat <<EOF

Usage: gh my failures [options]
  show workflow failures in your personal repositories in the last 14 days

  uses 'date' so any gnu date string is valid
  -d : the date string (default is "14 days ago")
  -g --all-orgs : ALL organisations that you belong to. This is potentially a time-consuming
                  and foolish move, so you have been warned.
                  To mitigate, you can also set 'GH_MY_IGNORE_ORGS' as an additional filter
                  (space separated), but the filter isn't that sophisticated.
  -j : output each row as a JSON object.
       (--jsonlines is also accepted)
EOF
  exit 2
}

query_failures() {
  local since
  local since_dateonly
  local jq_filter
  local gh_repos
  local query_all_orgs
  since='14 days ago'
  local output_format='table'
  while getopts 'd:gjh' flag; do
    case "${flag}" in
    d) since="${OPTARG}" ;;
    g) query_all_orgs='true' ;;
    j) output_format='json' ;;
    h) query_failures_help ;;
    *) query_failures_help ;;
    esac
  done
  since_dateonly=$(date --date="$since" '+%Y-%m-%d')
  jq_filter='.workflow_runs[] | "\(.repository.name)|\(.name)|\(.html_url)|\(.created_at | fromdateiso8601 | strflocaltime("%d %b %Y"))"'
  jsonlines_filter='.workflow_runs[] | {repository: .repository.full_name, workflow: .name, url: .html_url, created_at: .created_at}'

  if [[ "$query_all_orgs" == 'true' ]]; then
    gh_repos=$(helper::list_my_org_repos)
  else
    gh_repos=$(gh repo list --json "nameWithOwner" -q ".[] | .nameWithOwner")
  fi

  case $output_format in
  json)
    for gh_repo in $gh_repos; do
      failed_workflows=$(helper::gh_api "repos/$gh_repo/actions/runs?status=failure&created=>$since_dateonly")
      echo "$failed_workflows" | jq -c "$jsonlines_filter"
    done
    ;;
  *)
    {
      for gh_repo in $gh_repos; do
        failed_workflows=$(helper::gh_api "repos/$gh_repo/actions/runs?status=failure&created=>$since_dateonly")
        echo "$failed_workflows" | jq -r "$jq_filter"
      done
    } | column -s'|' -t -N "REPOSITORY,WORKFLOW,URL,WHEN"
    ;;
  esac
}
