#!/usr/bin/env bash

query_issues() {
  # shellcheck disable=SC2016
  local query='
query ($endCursor: String) {
  search(query: "is:open is:issue user:@me archived:false", type: ISSUE, after: $endCursor, first: 50) {
    edges {
      node {
        ... on Issue {
          number
          title
          author {
            login
          }
          createdAt
          url
          repository {
            nameWithOwner
            name
          }
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}'
  helper::std_output_format "$@"
  helper::std_graphql "$query"
}
