#!/usr/bin/env bash

query_deployments_help() {
  cat <<EOF

Usage: gh my deployments [options]
  list deployments awaiting action on the default branch

  -g --all-orgs : ALL organisations that you belong to. This is potentially a time-consuming
                  and foolish move, so you have been warned.
                  To mitigate, you can also set 'GH_MY_IGNORE_ORGS' as an additional filter
                  (space separated), but the filter isn't that sophisticated.
  -o : the organisation (e.g. -o my-company)
  -t : the topic  (e.g. -t my-terraform-repos)
  -r : a specific repository, but why not use gh run list instead?
EOF
  exit 2
}

query_deployments() {
  local org=''
  local topic=''
  local repo=''
  local query_all_orgs='false'

  for arg in "$@"; do
    shift
    case "$arg" in
    '--all-orgs' | '--allorgs')
      set -- "$@" '-g'
      ;;
    *) set -- "$@" "$arg" ;;
    esac
  done

  while getopts 'go:t:r:h' flag; do
    case "${flag}" in
    g) query_all_orgs='true' ;;
    o) org="org:${OPTARG}" ;;
    t) topic="topic:${OPTARG}" ;;
    r) repo="${OPTARG}" ;;
    h) query_deployments_help ;;
    *) query_deployments_help ;;
    esac
  done
  if [[ "$org" == "" && $topic = "" && $repo = "" && "$query_all_orgs" != 'true' ]]; then
    query_help
  fi
  if [[ $repo != "" ]]; then
    internal::repo_deploys "$repo"
  elif [[ "$query_all_orgs" == 'true' ]]; then
    my_orgs=$(helper::my_github_orgs)
    for github_org in $my_orgs; do
      queryString="org:${github_org} $topic"
      echo -e "\n🏛️ $github_org"
      internal::org_deploys "$queryString"
    done <<<"$my_orgs"
    echo ""
  else
    queryString="$org $topic"
    internal::org_deploys "$queryString"
  fi
}

# Query a specific repo for any deployments that are in a "waiting" state
internal::repo_deploys() {
  local repo="$1"
  # shellcheck disable=SC2016
  local deploy_template='{{tablerow "ID" "URL" "Branch" "When" -}}
{{ range . -}}
{{tablerow (.databaseId | autocolor "green") (.url | autocolor "cyan") (.headBranch | autocolor "yellow") (timeago .startedAt) -}}
{{end -}}'
  gh run list --repo "$repo" --json "databaseId,url,headBranch,startedAt" --template "$deploy_template" -s "waiting"
}

# Query the org, (filtering by topic) listing deployments in a waiting state that on the default branch
internal::org_deploys() {
  local queryString="$1"
  # shellcheck disable=SC2016
  local deploy_template='{{tablerow "ID" "URL" "Branch" "Repo" "Env" "Actionable" "When" -}}
{{range(pluck "node" .data.search.edges) -}}
{{ $repo:=.nameWithOwner -}}{{ $branch:=.defaultBranchRef.name -}}
{{range(pluck "workflowRun" .defaultBranchRef.target.checkSuites.nodes) -}}{{ $workflowId:= .databaseId -}}{{ $workflowRunURL:= .url -}}
{{range .checkSuite.checkRuns.nodes -}}
{{tablerow ($workflowId | autocolor "green")
          ($workflowRunURL | autocolor "cyan")
          ($branch | autocolor "yellow")
          $repo
          .pendingDeploymentRequest.environment.name
          .pendingDeploymentRequest.currentUserCanApprove
          (timeago .startedAt) -}}
{{end -}}
{{end -}}
{{end -}}
'
  # shellcheck disable=SC2016
  query='
query ($queryString: String!, $endCursor: String) {
  search(query: $queryString, type: REPOSITORY, first: 100, after: $endCursor) {
    edges {
      node {
        ... on Repository {
          nameWithOwner
          defaultBranchRef {
            name
            target {
              ... on Commit {
                checkSuites(filterBy: {appId: 15368}, last: 1) {
                  nodes {
                    workflowRun {
                      databaseId
                      url
                      checkSuite {
                        checkRuns(filterBy: {status: WAITING}, last: 1) {
                          nodes {
                            startedAt
                            pendingDeploymentRequest {
                              environment {
                                name
                              }
                              currentUserCanApprove
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}'
  gh api graphql --paginate -F queryString="$queryString" --raw-field query="$(helper::compressQuery "$query")" --template "$deploy_template"
}
