#!/usr/bin/env bash

query_issues_help() {
  cat <<EOF

Usage: gh my issues [options]
  list issues in your personal repositories

  -j : output each row as a JSON object.
       (--jsonlines is also accepted)
EOF
  exit 2
}

query_issues() {
  for arg in "$@"; do
    case "$arg" in
    -h) query_issues_help ;;
    esac
  done
  # shellcheck disable=SC2016
  local query='
query ($endCursor: String) {
  search(query: "is:open is:issue user:@me archived:false", type: ISSUE, after: $endCursor, first: 50) {
    edges {
      node {
        ... on Issue {
          number
          title
          author {
            login
          }
          createdAt
          url
          repository {
            nameWithOwner
            name
          }
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}'
  helper::std_output_format "$@"
  helper::std_graphql "$query"
}
